name: Post Data to API

on:
  push:
    paths:
      - 'test.txt' # Trigger the workflow when test.txt is pushed

jobs:
  post-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Post data to API endpoint
        run: |
          CONTENT=$(cat ./test.txt)
          JSON_STRING=$( jq -n \
                          --arg content "$CONTENT" \
                          '{data: $content}' )
          curl -X POST -H "Content-Type: application/json" -d $JSON_STRING https://duke2.free.beeceptor.com

