name: Monitor Text Files and Send Changes

on:
  push:
    paths:
      - 'app/**/*.txt' # Trigger the workflow for any .txt files in the app directory

jobs:
  send-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find Modified Text Files
        id: files
        run: |
          # 获取前一个提交的SHA
          PREV_SHA=$(git rev-parse HEAD^)
          # 获取当前提交的SHA
          CURRENT_SHA=$(git rev-parse HEAD)
          
          # 列出前一个提交和当前提交之间所有改动的.txt文件
          git diff --name-only $PREV_SHA $CURRENT_SHA -- 'app/*.txt' > changed_files.txt
          
          # 检查是否有文件改动
          if [ -s changed_files.txt ]; then
            echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
            cat changed_files.txt >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "No changes in .txt files detected."
          fi
      - name: Send File Contents to API
        run: |
          while IFS= read -r file; do
            if [[ -f "$file" ]]; then
              CONTENT=$(<"$file")
              JSON_STRING=$(jq -n --arg content "$CONTENT" --arg file "$file" '{file: $file, content: $content}')
              curl -X POST -H "Content-Type: application/json" -d "$JSON_STRING" https://duke2.free.beeceptor.com
            fi
          done <<< "$CHANGED_FILES"
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}
