name: Monitor Text Files and Send Changes

on:
  push:
    paths:
      - 'app/**/*.txt' # Trigger the workflow for any .txt files in the app directory

jobs:
  send-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
- name: Install jq
        run: sudo apt-get install jq

      - name: Find Modified Text Files
        id: find_modified_files
        run: |
          if git rev-parse --verify HEAD~1; then
            PREV_SHA=$(git rev-parse HEAD~1)
          else
            # If there is no previous commit, use the initial commit
            PREV_SHA=$(git rev-list --max-parents=0 HEAD)
          fi
          
          # Get the SHA for the current commit
          CURRENT_SHA=$(git rev-parse HEAD)
          
          # List all changed .txt files between the previous and current commit
          FILES=$(git diff --name-only $PREV_SHA $CURRENT_SHA -- 'app/*.txt')

          echo $FILES
