name: Monitor Text Files and Send Changes

on:
  push:
    paths:
      - 'app/**/*.txt' # Trigger the workflow for any .txt files in the app directory

jobs:
  send-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find Modified Text Files
        id: files
        run: |
          # Check if there is a previous commit to compare against
          if git rev-parse --verify HEAD^; then
            PREV_SHA=$(git rev-parse HEAD^)
          else
            # If there is no previous commit, use the initial commit
            PREV_SHA=$(git rev-list --max-parents=0 HEAD)
          fi
          
          # Get the SHA for the current commit
          CURRENT_SHA=$(git rev-parse HEAD)
          
          # List all changed .txt files between the previous and current commit
          git diff --name-only $PREV_SHA $CURRENT_SHA -- 'app/*.txt' > changed_files.txt
          
          # Check if the changed_files.txt file is non-empty (i.e., changes are detected)
          if [ -s changed_files.txt ]; then
            echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
            cat changed_files.txt >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "No changes in .txt files detected."
          fi
      - name: Send File Contents to API
        run: |
          while IFS= read -r file; do
            if [[ -f "$file" ]]; then
              CONTENT=$(<"$file")
              JSON_STRING=$(jq -n --arg content "$CONTENT" --arg file "$file" '{file: $file, content: $content}')
              curl -X POST -H "Content-Type: application/json" -d "$JSON_STRING" https://duke2.free.beeceptor.com
            fi
          done <<< "$CHANGED_FILES"
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}
